version: '3'

services:
  db:
    image: postgres:16-alpine
    container_name: vendas_db
    ports:
      - 5433:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: vendas_db
      POSTGRES_USER: vendas_db_user
      POSTGRES_PASSWORD: vendas_db_password

  backend:
    build: ./backend
    image: vendas_api_image
    container_name: vendas_api
    command: npm run start:dev
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    env_file:
      - ./backend/.env.development

volumes:
  db_data: